import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { RouterModule } from '@angular/router';

@Component({
  selector: 'app-catalogo',
  templateUrl: './catalogo.html',
  imports: [CommonModule, RouterModule],
  styleUrls: ['./catalogo.css'],
})
export class Catalogo {
  productos = productos;
}

export const productos = [
  {
    nombre: 'Aretes Corazón Colombia',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/acorazon.jpg',
    imagenAlt: 'assets/images/aretes/acorazon.jpg',
    coleccion: 'Colombia',
    precio: 18000,
  },
  {
    nombre: 'Aretes Cascada',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/cascada.jpg',
    imagenAlt: 'assets/images/aretes/cascada.jpg',
    coleccion: '',
    precio: 18000,
  },
  {
    nombre: 'Aretes Flor Blanca y Negra',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/florblancanegra.jpg',
    imagenAlt: 'assets/images/aretes/florblancanegra.jpg',
    coleccion: 'Flores',
    precio: 19000,
  },
  {
    nombre: 'Aretes Flor Roja',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/floroja.jpg',
    imagenAlt: 'assets/images/aretes/floroja.jpg',
    coleccion: 'Flores',
    precio: 17000,
  },
  {
    nombre: 'Aretes Flor Pastel',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/florpastel.jpg',
    imagenAlt: 'assets/images/aretes/florpastel.jpg',
    coleccion: 'Flores',
    precio: 17000,
  },
  {
    nombre: 'Aretes Frida',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/frida.jpg',
    imagenAlt: 'assets/images/aretes/frida.jpg',
    coleccion: '',
    precio: 17000,
  },
  {
    nombre: 'Aretes Hoja',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/hoja.jpg',
    imagenAlt: 'assets/images/aretes/hoja.jpg',
    coleccion: 'Flores',
    precio: 17000,
  },
  {
    nombre: 'Aretes Triangulares de Flores',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/triangularflores.jpg',
    imagenAlt: 'assets/images/aretes/triangularflores2.jpg',
    coleccion: 'Flores',
    precio: 18000,
  },
  {
    nombre: 'Aretes Árbol Navideño',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/aarbol.jpg',
    imagenAlt: 'assets/images/aretes/aarbol2.jpg',
    coleccion: 'Navidad',
    precio: 17000,
  },
  {
    nombre: 'Aretes Triangulares Navideños',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/atriangular.jpg',
    imagenAlt: 'assets/images/aretes/atriangular.jpg',
    coleccion: 'Navidad',
    precio: 17000,
  },
  {
    nombre: 'Aretes Galleta Navideña',
    tipo: 'aretes',
    imagen: 'assets/images/aretes/agalleta.jpg',
    imagenAlt: 'assets/images/aretes/agalleta.jpg',
    coleccion: 'Navidad',
    precio: 17000,
  },
  {
    nombre: 'Pulsera Chakras',
    tipo: 'pulsera',
    imagen: 'assets/images/pulseras/chakras.jpg',
    imagenAlt: 'assets/images/pulseras/chakras.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Pulsera Corazón Doble',
    tipo: 'pulsera',
    imagen: 'assets/images/pulseras/corazondoble.jpg',
    imagenAlt: 'assets/images/pulseras/corazondoble.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Pulsera Hexagonal',
    tipo: 'pulsera',
    imagen: 'assets/images/pulseras/hexagonal.jpg',
    imagenAlt: 'assets/images/pulseras/hexagonal2.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Pulsera de Letra Inicial',
    tipo: 'pulsera',
    imagen: 'assets/images/pulseras/letrainicial.jpg',
    imagenAlt: 'assets/images/pulseras/letrainicial.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Pulsera Telar',
    tipo: 'pulsera',
    imagen: 'assets/images/pulseras/pulseratelar.jpg',
    imagenAlt: 'assets/images/pulseras/pulseratelar.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Pulsera Tubular Azul',
    tipo: 'pulsera',
    imagen: 'assets/images/pulseras/tubular.jpg',
    imagenAlt: 'assets/images/pulseras/tubular.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Pulsera Tubular Colombia',
    tipo: 'pulsera',
    imagen: 'assets/images/pulseras/ptubular.jpg',
    imagenAlt: 'assets/images/pulseras/ptubular.jpg',
    coleccion: 'Colombia',
    precio: 25000,
  },
  {
    nombre: 'Pulsera Reno Navideño',
    tipo: 'pulsera',
    imagen: 'assets/images/pulseras/preno.jpg',
    imagenAlt: 'assets/images/pulseras/preno2.jpg',
    coleccion: 'Navidad',
    precio: 25000,
  },
  {
    nombre: 'Dije con Nombre',
    tipo: 'dije',
    imagen: 'assets/images/dijes/gargantillanombre.jpg',
    imagenAlt: 'assets/images/dijes/gargantillanombre.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Dije de Ojo Turco',
    tipo: 'dije',
    imagen: 'assets/images/dijes/ojoturco.jpg',
    imagenAlt: 'assets/images/dijes/ojoturco.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Unicornio Miyuki',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/unicorniomiyuki.jpg',
    imagenAlt: 'assets/images/Prendedores/unicorniomiyuki.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Llama Miyuki',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/llamamiyuki.jpg',
    imagenAlt: 'assets/images/Prendedores/llamamiyuki.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Mariposa Morada',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/mariposamorada1.jpg',
    imagenAlt: 'assets/images/Prendedores/mariposamorada2.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Mariposa Naranja',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/mariposanaranja.jpg',
    imagenAlt: 'assets/images/Prendedores/mariposanaranja2.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Colibri',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/colibri1.jpg',
    imagenAlt: 'assets/images/Prendedores/colibri2.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Calabaza',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/calabaza.jpg',
    imagenAlt: 'assets/images/Prendedores/calabazagrande.jpg',
    coleccion: 'Halloween',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Calabaza Pequeña',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/calabazapequeña.jpg',
    imagenAlt: 'assets/images/Prendedores/calabazapequeña.jpg',
    coleccion: 'Halloween',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Corazón Jeans',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/corazonjeans.jpg',
    imagenAlt: 'assets/images/Prendedores/corazonjeans2.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Corazón Azul',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/corazonazul.jpg',
    imagenAlt: 'assets/images/Prendedores/corazonazul.jpg',
    coleccion: '',
    precio: 25000,
  },
  {
    nombre: 'Prendedor Corazón Morado',
    tipo: 'prendedor',
    imagen: 'assets/images/Prendedores/corazonmorado.jpg',
    imagenAlt: 'assets/images/Prendedores/corazonmorado.jpg',
    coleccion: '',
    precio: 25000,
  },
];
